### ISSUE TITLE
test issues for jack

### ISSUE THREAD

**Issue by Danwhy** [dwyl/tudo#10]
@jrans you need more issues.

**Comment by jrans** [comment]
adding comment to see the object

**Comment by jrans** [comment]
@Danwhy just filling the issue object with more content to look at.
![10568831_10152600970189549_4248070944150361947_n](https://cloud.githubusercontent.com/assets/12045918/8800033/1ab29f76-2fa7-11e5-9ceb-2ab8aa8960b4.jpg)
