### ISSUE TITLE
Having issues coloured with their priority colour.

### ISSUE THREAD

**Issue by beechware** [dwyl/tudo#104]
Having the issue list item coloured with their priority colour. 
Later we decided to show the colour as a block (rectangle) on the left hand side. This is for readability.

However I think a light tint over the `<li>` item as well as the block wouldn't effect readability and would still make issues easier and more enjoyable to search through.

**Comment by beechware** [comment]
Having the issue list item coloured with their priority colour. 
Later we decided to show the colour as a block (rectangle) on the left hand side. This is for readability.

However I think a light tint over the li item as well as the block wouldn't effect readility and would still make issues easier and more enjoyable to search through.

**Comment by nelsonic** [comment]
@beechware agree this would be a great UI element, we are hoping to A/B test UI features so we should add this to the backlog once MVP is out! relates to: #98

**Comment by iteles** [comment]
I think we're going to need an A/B testing milestone/label at this rate :stuck_out_tongue:

**Comment by Cleop** [comment]
Closing as new UI incorporating priority label color has been created.
