### ISSUE TITLE
Information to go in an issue row

### ISSUE THREAD

**Issue by rjmk** [dwyl/tudo#106]
| Left | Middle | Right |
| :-- | :-: | --: |
| Colour Bar | [ORG/REPO NAME] Title of repo | to issue arrow |
| Colour Bar | Activity metric | to issue arrow |

**Comment by rjmk** [comment]
Look this is totally correct markdown. Github is being difficult

**Comment by iteles** [comment]
@rjmk I fixed your totally correct markdown. :stuck_out_tongue_closed_eyes:  #yourewelcome

<img width="801" alt="screen shot 2015-08-18 at 22 08 57" src="https://cloud.githubusercontent.com/assets/4185328/9342797/cf4e4156-45f5-11e5-927e-b54ce0a23a4d.png">

**Comment by iteles** [comment]
Links to https://github.com/dwyl/tudo/issues/103 on **activity metrics**.

**Comment by iteles** [comment]
https://github.com/dwyl/tudo/commit/06b2359123f9edd9d5c3fea8c8d2788bd8fc97f2 creates the basic HTML structure according to this

**Comment by rjmk** [comment]
@iteles Thanks! What did you change? I can't see the difference

**Comment by iteles** [comment]
@rjmk You need more than one hyphen in the 2nd line blocks for it to work :wink:

**Comment by iteles** [comment]
@rjmk What conditions are needed for this to be closed?

**Comment by rjmk** [comment]
I would argue that it is either already ready to be closed or should be closed when dynamically loaded tags have these rendering correctly.

**Comment by Jbarget** [comment]
closing as more up to date detail is covered in https://github.com/dwyl/tudo/issues/203
