### ISSUE TITLE
Create minimum html & css version of the issue list 

### ISSUE THREAD

**Issue by FilWisher** [dwyl/tudo#107]
We should begin with a minimal html layout with css to use as a base for developing before functionality.

**Comment by tsop14** [comment]
Re. CSS

http://colorbrewer2.org/ 

This has colorblind safe option. Good for picking colour scheme for priority levels.

**Comment by iteles** [comment]
@tsop14 Top find! :+1:

**Comment by iteles** [comment]
:+1: Closed by PR https://github.com/dwyl/tudo/pull/110
