### ISSUE TITLE
Tidy Up Time? (can we prune orphan branches?)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#112]
![tudo-branches-stale](https://cloud.githubusercontent.com/assets/194400/9354871/f647784c-466b-11e5-8994-6fa9e6e55969.png)

At present we have **_5 Orphan Branches**_ in the repo: https://github.com/dwyl/tudo/branches/all
Should we _retire_ them?

**Comment by tsop14** [comment]
The db-to-render branch has mock data from GitHub api, do we have this elsewhere? Good idea to prune. :palm_tree:

**Comment by rjmk** [comment]
I'm all for the prune; nothing looks particularly relevant to the current code.

**Comment by Cleop** [comment]
Closing as no longer have outstanding branches
