### ISSUE TITLE
Asynchronous calls in a forEach

### ISSUE THREAD

**Issue by rjmk** [dwyl/tudo#116]
We were discussing performance problems and mentioned going through the [issues in a forEach loop](https://github.com/dwyl/tudo/blob/master/lib/get_issues.js). I ended the conversation unsure whether the performance issue was just from registering asynchronous callbacks in a loop (and waiting for the slowest response) or if the forEach is somehow making the asynchronous calls synchronous. 

I assume the former but wanted to clarify.

Relatedly, what sort of spread on response times do we expect from github?

**Comment by iteles** [comment]
@rjmk What was the conclusion for this issue? :blush:
