### ISSUE TITLE
On login page, header and footer don't exist so 'undefined' appears.

### ISSUE THREAD

**Issue by FilWisher** [dwyl/tudo#118]
header.html and footer.html have been deleted. This is making 'undefined' appear at the top and bottom of the login page when visiting '/'

**Comment by beechware** [comment]
![Login page no header and footer](https://cloud.githubusercontent.com/assets/6025734/9359401/dab47f40-4688-11e5-9e72-03ba1d504d82.png)

**Comment by iteles** [comment]
Quick fix in root route `/`,

``` javascript
reply(tags.header + riot.render(tags.login, {GITHUB_CLIENT_ID:process.env.GITHUB_CLIENT_ID}) + tags.footer)
```

to

``` javascript
reply(tags.prefix + riot.render(tags.login, {GITHUB_CLIENT_ID:process.env.GITHUB_CLIENT_ID}) + tags.suffix)
```
