### ISSUE TITLE
Can we Concierge this By Manually Adding Priorities to all the Issues in dwyl/tudo?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#126]
Manually work through adding priority

See: http://ibuildmvps.com/blog/the-concierge-minimum-viable-product-maximizes-customer-learning

**Comment by iteles** [comment]
Done by the lovely **dwyl/summerers** @dwyl/summer earlier today :+1: 
<img width="514" alt="all-issues-with-priorities" src="https://cloud.githubusercontent.com/assets/4185328/9388906/20a01104-4760-11e5-84de-a6adfce670f5.png">

**Comment by Cleop** [comment]
Closing as historic
