### ISSUE TITLE
Storing Issues

### ISSUE THREAD

**Issue by NataliaLKB** [dwyl/tudo#13]
Hi @nelsonic,

It's @jrans, we spoke briefly earlier in person.

Each issue is approx 4605 characters/bits or 570bytes. Do we store the whole thing? Just the title and time last edited..?

Up for discussion but nice to know our space limitations.

Best Wishes,

Jack

**Comment by nelsonic** [comment]
@jrans or @NataliaLKB could you please upload a sample file? _thanks_

**Comment by NataliaLKB** [comment]
@nelsonic sample file provided in #16 here: https://github.com/dwyl/tudo/blob/githubIssuesAPI/exampleIssue.json

**Comment by nelsonic** [comment]
![example-issue-json-404](https://cloud.githubusercontent.com/assets/194400/8846973/ce7ec4fe-3122-11e5-84ea-cbae11a2b48b.jpg)

When referencing a file on GitHub, _always_ include the commit hash in the url ... otherwise :panda_face: :cry: 

> e.g: https://github.com/dwyl/tudo/blob/b1de331159b6398abbc13e9a8a1ddf5e59251b82/exampleOfBasicIssue.json

thanks. :+1:

**Comment by NataliaLKB** [comment]
@nelsonic thanks that is a helpful hint! 

@jrans has this questions been answered satisfactorily? Is this ready to close?

**Comment by NataliaLKB** [comment]
@jrans closing for now. Do reopen if you discover things are missing.
