### ISSUE TITLE
should 'unprioritised' be represented with a question mark? 

### ISSUE THREAD

**Issue by minaorangina** [dwyl/tudo#130]
This might cause issues if a user wants to get to unprioritised issues by typing a '?' in the url.

**Comment by nelsonic** [comment]
It appears we have created two similar issues: #131 with a _suggested alternative_ :wink: 
thanks for creating this issue @minaorangina :+1:

**Comment by nelsonic** [comment]
I suggest we use `PU` as the label on the (Mobile) Client to indicate an issue the is "Priority Undefined".

**Comment by iteles** [comment]
:+1:

**Comment by Cleop** [comment]
Closing as covered in #131
