### ISSUE TITLE
Tidy up redis connection in lib/redis_config.js

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#137]
See: https://github.com/dwyl/tudo/blob/e8a54f2b748396e560911b34efd49ed91de94f07/lib/redis_config.js#L3
This should url.parse(d) in situ.

**Comment by nelsonic** [comment]
Remove references to `TEST_REDISCLOUD_URL` as we are _always_ using a Test instance during dev/test...
<img width="894" alt="screen shot 2015-08-27 at 15 39 54" src="https://cloud.githubusercontent.com/assets/194400/9523533/625baae6-4cd2-11e5-8a07-15e35132795d.png">

**Comment by Jbarget** [comment]
closing as related to old hapi project and we're currently re writing in elixir
