### ISSUE TITLE
Define what priority labels mean for *dwyl*

### ISSUE THREAD

**Issue by iteles** [dwyl/tudo#140]
So we can start using the priority labels (1-5) across our repos.

**Comment by iteles** [comment]
Here's a start, completely up for discussion:
- **Priority 1:** STOP. This is preventing **EVERYONE** from using the app or core functionality is breaking (our app is offline, people can't log in/view their issues). Do not do **anything** until this is fixed.
- **Priority 2:**  Issue is in the **core functionality** or is affecting 60% or more of people using the app
- **Priority 3:** Issue is non core or affecting less than 40% of people using the app 
- **Priority 4**: Issue is non core and affecting less than 10% of people using the app
- **Priority 5:** This is where ideas for the future live

Of course, this implies defining _core functionality_,

Thoughts welcome!

**Comment by iteles** [comment]
@nelsonic Any thoughts on this? I'm happy to go with something completely different but I'd like to roll out the priority labels to all dwyl's repos and it would be good if we could define a reasonably solid _starting point_ which we can adapt as we use them.

**Comment by nelsonic** [comment]
Are you going to "_roll out_" the Labels using `code` or _manually_...?

**Comment by iteles** [comment]
I mentioned a while ago that it would be a good thing to write a little module for. We can't be the only organisation with this issue...!

Either way I'm very much missing the labels on our ongoing projects.

**Comment by iteles** [comment]
Moved this to https://github.com/dwyl/process-handbook/issues/76 for now 👍
