### ISSUE TITLE
Can we replace old master

### ISSUE THREAD

**Issue by des-des** [dwyl/tudo#156]
As requested we are pushing our code to this repo.
This means there are two parallel histories happening. Are we good to delete the old master here, or should we continue development in another repo?

**Comment by nelsonic** [comment]
@des-des merging your work into master will get what we need.
Deleting the "old" `master` will delete previous contribution which is _not_ what we want to do.
For an Open Source project to be successful it has to have _several_ contributors to _attract_ more contributions...

**Comment by des-des** [comment]
Done!
