### ISSUE TITLE
Ecto Schema

### ISSUE THREAD

**Issue by Jbarget** [dwyl/tudo#165]
We need to decide what fields we want to store in our database

This is what we get back for each issue at the moment: https://developer.github.com/v3/issues/#response-1

@nelsonic are there any specific requirements for future iterations that we should be aware of, or is this just a prototype?

**Comment by des-des** [comment]
I think lets work backwards from what we want to display.
Off the top of my head
for each issue: repo, repo link, assignee handles, labels, issue number, issue link, issue description.

I see the tables: issues, repos, users, labels.

**Comment by nelsonic** [comment]
@Jbarget we cannot _predict_ future requirements that will _emerge_ from usage.
If _I_ was writing this I would ask a different question: can I write a function to take a sample (JSON) response from GitHub and convert each field into an Ecto (Phoenix Model) data type so we can "_store everything_"?

I _like_ the approach suggested by @des-des as it's "_minimalist_" and focusses on _current_ requirements.
Go with that and we can always add more fields as required later. 👍

**Comment by Jbarget** [comment]
sounds good, just getting everything in place so regardless of who's working on the features we know what we're doing

**Comment by Cleop** [comment]
Update:

- 4 x tables - repos, issues, labels, label and issue id's
- Stored info:
  - repositories: repository, url
  - issues: assignees, labels, issue number, issue link, issue description.
  - labels: name, color hex code
  - label and issue id table: issue id, label id's

**Comment by Jbarget** [comment]
Issue schema:
```
title:string
url:string
labels:array:strings (strings made from "{colour},{name of label}")
gh_created_at:date
gh_updated_at:date
comments_number:integer
state:string
assignees:array:string (strings made from "{avatar url};{login handle}")

```
**Out of scope:**

Repo schema:
```
name:string
url:string
```

labels: 
```
name: string
color hex code: string
```
label and issue id table:
```
 issue id: integer
 label id's: array: integers
```

**NB** issue schema for labels needs to change to `labels:array:integer`

**Comment by Jbarget** [comment]
We have decided on a single table called `issues` for MVP with the schema here: https://github.com/dwyl/tudo/issues/165#issuecomment-318841138

**Comment by Jbarget** [comment]
Closing as schema confirmed and implemented as above
