### ISSUE TITLE
Add dwyl favicon

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#170]
![image](https://user-images.githubusercontent.com/16775804/28720373-e7b166c2-73a4-11e7-9b59-1fee3c276652.png)

- [x] Add the same favicon as the one found on the dwyl site

**Comment by Jbarget** [comment]
![screen shot 2017-07-29 at 14 23 36](https://user-images.githubusercontent.com/11725595/28745131-87981c84-7469-11e7-828b-de6a34877d61.png)

all good 👍
