### ISSUE TITLE
Research into API understanding of 'last updated'

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#174]
Research into API understanding of 'last updated' so that we can establish whether looking for updates will include updates to issues/ labels or just code.

**Comment by samhstn** [comment]
In terms of sending one request to get information about all repos, using something like:

```bash
curl https://api.github.com/orgs/dwyl/repos\?page_results\=100
```
(we will have to make 3 requests like this with `page=2` and `?page=3` as additional query params to get all of the dwyl issues)

The [`updated_at`](https://developer.github.com/v3/repos/#list-contributors) property only reflects changes which have made in terms of code and is not affected by issue changes.

We can however get all the necessary information by making subsequent requests for each individual repo, but this will take a long time so we don't want to make these more detailed requests for each repo.

We can however get the number of opened issues for each repo with just one request through the `open_issues` property, this could perhaps be an indication as to weather a repo has had updates and that we could do a diff on this property with what we have stored in our db and what the github one is and subsequently do additional requests for more up to date data.

**Comment by Cleop** [comment]
Closing as no longer need to use the last_updated property as we'll be using the webhook api for updates.
