### ISSUE TITLE
Display 10 'help-wanted' issues (one page)

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#176]
Display 20 'help-wanted' issues (one page) based on data stored in db (#149).

Need to determine in what order repos should be displayed.

# Acceptance Criteria

- [x] Display 20 issues
- [x] Style in a table

**Comment by nelsonic** [comment]
@Cleop ***how many rows*** do you `expect` will fit on an **iPhone 5** (C/S/SE) screen including basic "menu" UI without/before scrolling? 🤔

**Comment by Cleop** [comment]
Sorry @nelsonic, good point. I should have made this clearer, we will display fewer on mobile.

**Comment by Jbarget** [comment]
we have adjusted getting 20 issues per page to 10 for MVP as @nelsonic makes a very valid point
