### ISSUE TITLE
Storing credentials?

### ISSUE THREAD

**Issue by NataliaLKB** [dwyl/tudo#18]
Are we using [env](https://www.npmjs.com/package/env), [config](https://www.npmjs.com/package/config), or a config.json (as currently in the `githubIssuesAPI` branch

**Comment by nelsonic** [comment]
I've shared a Google Doc: https://docs.google.com/document/d/1uztGvSE8nxjQwJtCorQUiNM9irjIoomhFuhLfghDC0o
With you which contains the env.json which you can copy paste.
The `.gitignore` should prevent people from accidentally adding the secret keys to GitHub.

Please share the Google Doc with the relevant people so they can run the app.
Thanks! :+1:

**Comment by NataliaLKB** [comment]
@jrans, shall we do this now on your laptop?

**Comment by NataliaLKB** [comment]
@nelsonic should be shared with the relevant people now!

**Comment by nelsonic** [comment]
@NataliaLKB can we close this now? :+1:

**Comment by NataliaLKB** [comment]
Closing as we have decided on using `env.json`
