### ISSUE TITLE
Add dwyl-site colors

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#182]
- [x] Add dwyl-site colors

**Comment by iteles** [comment]
Can we get a mini style/colour guide in the readme with this too please? 🙏

**Comment by Jbarget** [comment]
all good 👍 
![screen shot 2017-07-29 at 14 23 59](https://user-images.githubusercontent.com/11725595/28745132-985551e0-7469-11e7-84c4-fbfe7e30476f.png)

**Comment by iteles** [comment]
@jbarget Did you see my comment above?

**Comment by Jbarget** [comment]
:) https://github.com/dwyl/tudo/issues/193

slipped through the net, soz
