### ISSUE TITLE
Pagination UI and functionality

### ISSUE THREAD

**Issue by samhstn** [dwyl/tudo#189]
As a user

I want to be able to see 20 issues at a time, with the ability to go from page to page

so that there is not too much information on the screen at one time.

- [x] Calculate number of pages based on number of issues (25m)
- [x] Display sed number of page numbers (1h)
- [x] Build functionality so the page number corresponds to correct results (2h)
- [x] UI for pagination (25m)
- [x] See which page I am currently on (1h)
- [x] Functioning 'next' 'prev' buttons as well as pages (1h)
- [x] Ellipses for when there are more than 5 pages (1h)
![screen shot 2017-07-29 at 15 02 37](https://user-images.githubusercontent.com/15983736/28745375-fb699ca0-746e-11e7-90f7-efdfca9d8dbb.png)

**Comment by Jbarget** [comment]
adjusting priority of this functionality as we've realised in order to display more than 10 results on mobile this will be key

**Comment by samhstn** [comment]
This is how pagination was implemented in the Science museum: https://github.com/TheScienceMuseum/collectionsonline/blob/master/lib/pagination.js

The tests for it would probably be more useful though: https://github.com/TheScienceMuseum/collectionsonline/blob/master/test/pagination.test.js

**Comment by Jbarget** [comment]
Ive just found this library that may make our lives easier: https://hexdocs.pm/rummage_phoenix/1.2.0/Rummage.Phoenix.html

Adds phoenix support for Search, Sort and Pagination

`Rummage.Phoenix is a support framework for Phoenix that can be used to manipulate Phoenix collections and Ecto models with Search, Sort and Paginate operations.`

If we need to revert we have this commit with vanilla elixir/phoenix functionality to show the correct amount of pages depending on the amount of rows in the DB: https://github.com/dwyl/tudo/commit/ee51e20da77c708ef8df6d43acdf31d8fdd85f23

**Comment by Jbarget** [comment]
Im going to spend an hour investigating the library above.

**Comment by Jbarget** [comment]
Initial pass at using the library went well, however we have hit a blocker in getting the library to run with the latest version `1.2.0`.

I believe its worth sticking with the library as in the long run it provides search, filter and pagination without much effort.

I've opened an issue on the repo here and hoping for an answer 🤞 : https://github.com/aditya7iyengar/rummage_phoenix/issues/36

Current working state of pagination gives us:
- unstyled page numbers at the bottom of the list of issues
- functionality to retrieve the correct "page" of issues from the DB

**Comment by Jbarget** [comment]
have reverted back to version `1.0.0` for now: and will work on styling for page numbers

![screen shot 2017-08-03 at 11 06 11](https://user-images.githubusercontent.com/11725595/28916933-c9abbf88-783b-11e7-8a8e-9de9489f34ee.png)

**Comment by Jbarget** [comment]
NB: https://github.com/dwyl/tudo/issues/206

**Comment by Jbarget** [comment]
We have a reply from the author of the `rummage` module: https://github.com/aditya7iyengar/rummage_phoenix/issues/36#issuecomment-320453712

**Comment by Jbarget** [comment]
got version 1.2 giving back a list of issues but no pagination yet, asked another question on the same issue: https://github.com/aditya7iyengar/rummage_phoenix/issues/36#issuecomment-323346400

**Comment by ZooeyMiller** [comment]
@finnhodgkin and I are looking into writing a helper function for adding the ellipses for more than 5 pages, it's an [issue in `rummage`](https://github.com/aditya7iyengar/rummage_phoenix/issues/30) that it doesn't exist, but they suggest making a helper function. 
(A lot of time estimates on here so will add as comment)

~PT1h~ PT2h

EDIT: I definitely underestimated how complex implementing my own helper function for this would be...

**Comment by finnhodgkin** [comment]
Rummage v1.2 with max pagination links is now working :+1:

AT2H

**Comment by hanman18** [comment]
Any easy ways to convert /example?rummage[paginate][page]=2  to /example?page=2 with this library?

**Comment by samhstn** [comment]
Hi @hanman18 👋

I would say that it wouldn't be that easy. It all looks hardcoded in this file: https://github.com/aditya7iyengar/rummage_phoenix/blob/master/lib/rummage_phoenix/hooks/views/paginate_view.ex (in places like [here](https://github.com/aditya7iyengar/rummage_phoenix/blob/master/lib/rummage_phoenix/hooks/views/paginate_view.ex#L61) for example)

If you post an issue the [aditya7iyengar/rummage_phoenix](https://github.com/aditya7iyengar/rummage_phoenix/issues) library, you may get an answer for how you could get around this problem

Let us know if you manage to find a nice way to solve this, the tudo app functioning with that url conversion would be very nice to have 👍

**Comment by Jbarget** [comment]
@hanman18 @shouston3 linked to: https://github.com/dwyl/tudo/issues/206
