### ISSUE TITLE
Transfer ownership of Github Tudo app to DWYL

### ISSUE THREAD

**Issue by Jbarget** [dwyl/tudo#195]
@iteles

Eoin created the application on github and has now transfered it to me, i've asked to transfer ownership to `dwyl`

![screen shot 2017-07-30 at 16 33 50](https://user-images.githubusercontent.com/11725595/28754811-170fd646-7545-11e7-831a-5159ce7a684a.png)

**Comment by iteles** [comment]
<img width="237" alt="screen shot 2017-08-09 at 14 06 22" src="https://user-images.githubusercontent.com/4185328/29122945-fbbae9b6-7d0b-11e7-9741-ccc827c358fb.png">
