### ISSUE TITLE
Bug for when an organisation has exactly a multiple of 100 repos ie. 200, 300

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#196]
<img src="https://user-images.githubusercontent.com/16775804/28822932-230678e6-76b3-11e7-8439-53d3cfa3604f.png" width=450px />
This code to work out how many pages to query the github api for according to how many repos your org has. Currently it will look for more pages of repos if the last page had 100 repos. As a result if you happen to have precisely 100 or 200 etc. repos in total then currently you will get stuck in a perpetual loop. This needs fixing.

**Comment by samhstn** [comment]
@Cleop I've rethought the logic for this and implemented it here: https://github.com/dwyl/tudo/pull/201/files#diff-22335f36da358ea6c44d3e3b6d9fe09cR43

I've also added tests for the multiple of 100 repos scenario here: https://github.com/dwyl/tudo/pull/201/files#diff-55636695cd0112390874b645aaeed25aR28

Perhaps this can be closed when #201 is merged

**Comment by samhstn** [comment]
@Cleop can we close this?
