### ISSUE TITLE
Web hooks for new issues

### ISSUE THREAD

**Issue by jrans** [dwyl/tudo#21]
@nelsonic @benjaminlees Will you add a webhook on initial authorisation to notify us of the creation of new issues?

**Comment by nelsonic** [comment]
@jrans yes! please add links to API docs for how to do this. :+1:

**Comment by nelsonic** [comment]
@Danwhy a little bird tells me you might be investigating this...? :wink:

**Comment by Danwhy** [comment]
@nelsonic I used webhooks in week 7, and have an example of it here:
https://github.com/Danwhy/issue-alert/blob/master/server.js#L12-L34  
The docs: 
https://developer.github.com/webhooks/creating/

**Comment by nelsonic** [comment]
Sweet. thanks. :+1:

**Comment by iteles** [comment]
Unassigned @jrans as @Danwhy provided the answer above (thanks!).
Issue not closed as not yet incorporated.

**Comment by Jbarget** [comment]
moving this work to: https://github.com/dwyl/tudo/issues/180 and https://github.com/dwyl/tudo/issues/179

webhook API has changed as well so will look at the updated docs
