### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by samhstn** [dwyl/tudo#211]
We will need to run the seed file on heroku when deploying and simultaneously set up webhooks on all dwyl repos.

All the logic for this has been built and tested as of #201

**Comment by samhstn** [comment]
Will also need to ensure to clean up webhooks attached to repos and ensure there is space for the new ones

**Comment by samhstn** [comment]
@nelsonic should we deploy now to be able to use the app or should we wait for https://github.com/dwyl/tudo/issues/197#issuecomment-320440560 to be addressed (it will still be very useable without this)?

**Comment by iteles** [comment]
@shouston3 Yes, let's definitely deploy what we have please 😊 
Can't do internal user testing without it!
Can we simultaneously also update the readme to explain the current limitations and refer to the issues?

**Comment by samhstn** [comment]
Will do 👍

**Comment by samhstn** [comment]
@Jbarget has made progress with the deployment. Just need to remove the other hooks on the dwyl repos and run the seed file with the new hooks

**Comment by samhstn** [comment]
@ZooeyMiller @finnhodgkin Steps to deploy the app are roughly as follows:

You'll first need to run some things from the IEx shell (`iex -S mix`) locally, run something like
```elixir
alias Tudo.{GithubApi, Hook}
"dwyl" |> GithubApi.get_repos |> Enum.filter(some_filter) |>  Hook.delete(some_url)
```
Essentially remove all the webhooks that are pointing at a `ngrok` server and instead add hooks that point to the heroku app instead.
Check out how to do that in this file: https://github.com/dwyl/tudo/blob/master/web/github/hook.ex
and here: https://github.com/dwyl/tudo/blob/master/web/github/github_api.ex#L43
Also when you manage that, could you update the readme with how to do this dwyl/tudo#213

Let me know how you get on and post any questions here if they pop up

**Comment by finnhodgkin** [comment]
Thanks Sam, sounds clear enough! We'll have a go now :+1:

**Comment by samhstn** [comment]
From this question:

```
We tried accessing it using the env variables saved on the heroku app but they're
giving us non-responses from github
({"documentation_url", "https://developer.github.com/v3"}).
Maybe we're doing something else wrong, or the heroku setup is out of date.
Should we just make our own temporary ones (didn't seem to work) or
are there some working env vars with appropriate permissions?
```

You might need to ensure that your github account has the appropriate access and that your personal access token also has the appropriate access.

Can you provide example requests that you are sending which should be working, but aren't. E.g.

```bash
curl https://api.github.com/orgs/dwyl/repos\?page_results\=100\&page\=2 # gives us 404 ?
```

**Comment by finnhodgkin** [comment]
Pretty sure the Heroku access_token has been revoked and Zooey and I don't have permissions for dwyl github things.

It works perfectly on my own repos :+1:

**Comment by samhstn** [comment]
I see, you'll need to get 2 factor auth and approved by @iteles or @nelsonic to be allowed to have write access to dwyl repos. I'll share one of my pa keys for now so you can continue.

**Comment by ZooeyMiller** [comment]
Are we adding a webhook to point to https://tudo-app.herokuapp.com/ rather than the ngrok server, if a repo doesn't have an ngrok webhook are we still adding the heroku webhook, or only to those that currently have an ngrok webhook?

**Comment by samhstn** [comment]
Add the webhook pointing to https://tudo-app.herokuapp.com/ to all dwyl repos and remove any webhooks on dwyl repos which have ngrok server references (these were just set up for testing and the server no longer exists).

**Comment by ZooeyMiller** [comment]
it's taking a little longer than expected just because the code doesn't deal with unexpected results well (if there are no webhooks for a repo then Hook.delete/2 errors), so we're having to work on the code to make sure it doesn't error with any input. Also lunch.

**Comment by samhstn** [comment]
No worries at all, perhaps look at adding a `somefilter` function from [this comment](https://github.com/dwyl/tudo/issues/211#issuecomment-325629709) to ensure that the correct hook exists for that repo. Or yea, look at fixing the `delete` function

**Comment by finnhodgkin** [comment]
So I've deleted and created webhooks for all dwyl repos that the access token you gave me had permissions for.

About a third of them won't respond. I don't know what the key difference is between repos that do respond and those that don't (for example learn-tdd and learn-tape don't, but learn-redux does). Do you have to enable webhooks for repos? Would be strange because lots of repos that had no webhooks before - learn-redux, etc - now have the new one. 

![weird](https://user-images.githubusercontent.com/22300773/29865455-7dd3c3a2-8d6d-11e7-9762-4f83c747eb51.png)

**Comment by Jbarget** [comment]
@finnhodgkin are the results you found above consistent?

What do you mean in this context by "wont respond"?

**Comment by finnhodgkin** [comment]
As in the picture above some repos like learn-tape and learn-tdd won't respond to `Hook.get`, `Hook.delete`, etc. I'm guessing it's something to do with permissions :woman_shrugging: 

It seems consistent so far:

![testing](https://user-images.githubusercontent.com/22300773/29867001-1b80580a-8d72-11e7-916f-2c41646eea42.gif)

It's always the same repos that don't respond.

**Comment by Jbarget** [comment]
👍  permissions sounds logical, lets see what @shouston3 says

**Comment by samhstn** [comment]
It does seem like a permissions issue as for the repositories which I am getting this response

![screen shot 2017-08-30 at 14 00 21](https://user-images.githubusercontent.com/15983736/29873601-bcd073a2-8d8b-11e7-9de5-311c9f039bba.png)

I also don't have a `settings` tab in the github navbar.

![screen shot 2017-08-30 at 14 01 55](https://user-images.githubusercontent.com/15983736/29873625-d37b95f0-8d8b-11e7-9f61-28c0c6a9e9c4.png)

Whereas I have a settings bar for repos which I can access the webhooks for.

One strange thing is that we are getting a 404 error and not 401 unauthorised error

@nelsonic @iteles @markwilliamfirth could one of you try sending the exact same postman request but with your username and personal access token as the password and see if you get a different response (or anyone else with admin access or a settings tab on `dwyl/learn-tdd` @SimonLab?).

**Comment by samhstn** [comment]
Nice spot btw @finnhodgkin @ZooeyMiller

**Comment by Danwhy** [comment]
It looks like webhooks need admin access to repos: https://developer.github.com/v3/orgs/hooks/, and it also looks like the `core` dwyl team doesn't have admin access to all repos: https://github.com/orgs/dwyl/teams/core/repositories. This would make sense of the problems @finnhodgkin was having (the `core` team only have write access to `learn-tdd` and `learn-tape`, but admin access to`learn-redux`).

So to fix this permissions issue we'd need to use an access token from either an owner of the dwyl organisation, or somebody with admin access to all of the repos

**Comment by iteles** [comment]
Thanks for the summary @Danwhy! Agreed that an owner token probably makes more sense as Nelson and I for example will (hopefully) be a constant and we won't need to keep swapping them around. Let's work to get you what you need (as long as we limit the access to the minimum set and if tudo is hacked they can't go deleting all our repos)!

**Comment by iteles** [comment]
Done for the following & sent to @Danwhy : 
<img width="437" alt="screen shot 2017-11-10 at 12 11 08" src="https://user-images.githubusercontent.com/4185328/32658126-7fcefb8c-c610-11e7-857c-7f231800f5ab.png">

**Comment by Danwhy** [comment]
I think we'd just need access to repo hooks and org hooks. That shouldn't be a security issue as webhooks just send information to us, and don't allow any write access.

@shouston3, @finnhodgkin, @ZooeyMiller, @Jbarget Can you confirm those are the only permissions we need?

**Comment by samhstn** [comment]
@Danwhy I think those permissions will be all we need

**Comment by iteles** [comment]
Thank you both! (hai @shouston3 👋 Hope you're well!)

**Comment by Danwhy** [comment]
All current repos now have the webhook attached to them, and the database should be completely up to date with all of the current issues

**Comment by samhstn** [comment]
All looking deployed to me, nice @Danwhy 👍 

Tested on https://tudo-app.herokuapp.com
