### ISSUE TITLE
Add the ability to filter by repo

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/tudo#220]
As a developer who wants to help dwyl out with `help wanted` issues
I want to be able to filter issues by repo
So that I can see `help wanted` issues only on the repos my skills are relevant to.

**Comment by ZooeyMiller** [comment]
[Rummage](https://github.com/aditya7iyengar/rummage_phoenix) has a really nice search function, we just want to adapt it so that it has an autocomplete so that people can easily find which repos have open issues, without having to know precisely which term to search for.

**Comment by iteles** [comment]
Might also be worth considering how this could be done without rummage (even if just and implentation plan and time estimate at this stage) - whilst using rummage is nice, it doesn't teach you a whole lot other than how to use rummage 😉

**Comment by ZooeyMiller** [comment]
@iteles good point! We'll give it a go without just straight up using rummage then.

**Comment by ZooeyMiller** [comment]
We've had a working solution for a little bit, using a mix of rummage and our own code. It's hard to get out of using rummage _completely_ because our pagination and everything relies on it, but by creating our own form and endpoint we have a bit more control over it. 

We're now just looking into updating the tests for the `page_controller` to get us back up to 100% coverage, this kind of testing in Elixir is new to us, so it's proving a little more time consuming than first expected.
