### ISSUE TITLE
Have an option to show issues with no labels

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/tudo#229]
As a person who values organisation via labels
I want to be able to have an option to see only issues with no labels (often these issues are _actually_ in need of a `help wanted` label)
So that they can be given the appropriate labels

(taking longer than expected. Updated PT to 1d from 2h because of higher complexity than originally perceived.)

**Comment by ZooeyMiller** [comment]
While working on this feature we found that if an issue has a label removed, we update it in the database so that the labels for the issue in our db match those on github, but we do not check if the issue no longer has the `help-wanted` label, in which case it should be removed from the `issues` table in the database since it is no longer `help-wanted`.

Since we are working a lot on this file to add the no-labels feature we will update this in the same PR. 

```elixir
  @doc"""
  Called when an issue has a label removed
  """
  def create(conn, %{"action" => "unlabeled",
                     "issue" => %{"html_url" => html_url,
                                  "updated_at" => gh_updated_at,
                                  "labels" => labels}}) do

    labels = Enum.map labels, &GithubApi.format_label/1

    Issue
    |> Repo.get_by!(url: html_url)
    |> Issue.changeset(%{labels: labels, gh_updated_at: gh_updated_at})
    |> Repo.update!

    render conn, "index.json"
  end
```

**Comment by ZooeyMiller** [comment]
Having set up the hooks, we're now looking at setting up a seed script to fill up our database table with all of the issues with no labels. It seems there is no way to specifically get all issues with no labels from a repo, so we'll just have to get all issues and filter them to ones with no labels in Elixir. This is a seed script so will only be run once, so shouldn't be too much of a problem.

**Comment by ZooeyMiller** [comment]
Commit made, but need to test `get_all_repos` with Httpoison.

**Comment by finnhodgkin** [comment]
Test made. Bored on the train on the way home :smile:

**Comment by ZooeyMiller** [comment]
Ended up taking some extra time due to https://github.com/dwyl/tudo/pull/236#pullrequestreview-62169260

Which were then followed by travis problems. All tests passing and 100% coverage locally, but failing travis build. Had to do trial and error with pushing up to get travis passing which took some extra time too.

**Comment by ZooeyMiller** [comment]
Due to changes made in #237 we now have an option to view unlabelled issues, but the unlabelled issues are still displayed in the `help wanted` view.

We need to look into filtering the issues so that in the `help wanted` view we actually only see help wanted issues.
