### ISSUE TITLE
Filter results by label/s

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/tudo#238]
As a person who values organisation via labels
I want to be able to have an option to see only issues with certain labels
So I can work on `high priority` issues or those without an `in-progress` label.

**Comment by iteles** [comment]
@finnhodgkin I would suggest that the labels that appear on issues are also clickable, so that if I click on a label, it will filter by that label 👍

**Comment by finnhodgkin** [comment]
@iteles Great idea!

Searching by labels is proving difficult because Ecto doesn't have many query options for postgres arrays. We're building our own filtering which we'll hopefully be able to force into playing nicely with the pagination setup.

**Comment by ZooeyMiller** [comment]
Unfortunately the way we've written our filtering function (filtering the issues so that only those with X labels are shown) it runs on the results of the query to the database that rummage does, which means we filter a list of twenty results, those for the individual page, which is not what we need.

It seems regarding this feature we may have to do a major overhaul in which we essentially bypass rummage. The problem is that almost all of the rest of the functionality in terms of searching/sorting/pagination comes from rummage, which would mean we would probably then have to re-implement all of those things ourselves, which would prove time consuming to say the least.

**Comment by finnhodgkin** [comment]
It's a pretty central feature and I can't see any way to do it without doing all of the above :cry: .

**Comment by iteles** [comment]
@finnhodgkin @ZooeyMiller Does your original time estimation still hold for this?
Could you please write out your implementation checklist so that we can ask @shouston3 to have a quick look through before we spend further time implementing?

**Comment by finnhodgkin** [comment]
It probably ended up more like 6hrs. The central functionality and tests are there but it still needs a bit of polish:
* issues can't be sorted while label filtering is on
* label checkboxes don't retain state between pages
* the coloured labels aren't clickable

I'm also not that happy with [my implementation](https://github.com/dwyl/tudo/compare/filter-by-labels). Although it works it involves quite a lot of filtering and database queries so I'm not sure how performant it is. If anyone can think of a nicer solution to any of the below, that'd be amazing:
- [x] filter issues by labels using a set of label checkboxes
- [ ] also allow label filtering via the coloured label tags shown on each issue
- [x] save checkboxes between views to show which labels are filtered
- [ ] keep pagination, sorting and repo-name search working _with_ label filtering

**Comment by finnhodgkin** [comment]
I'm happy to pause this issue and work on something else while waiting for feedback / ideas :smile:.

**Comment by iteles** [comment]
@finnhodgkin What do you need feedback on? Whether the above bullets are necessary?

**Comment by finnhodgkin** [comment]
Implementation. Sorry I was just editing the comment above to include a checklist.

**Comment by finnhodgkin** [comment]
This is the last thing on my list that doesn't require a merge or feedback so I'll hop back to it for now:+1:

**Comment by iteles** [comment]
@shouston3 If you have a little time to lend us your wisdom on the implementation side of this as mentioned in https://github.com/dwyl/tudo/issues/238#issuecomment-329474169, that would be wonderful

**Comment by finnhodgkin** [comment]
I ran out of other issues that don't require a merge / feedback so I hopped back onto this. Issues now retain checks between pages so there are only a couple of todos to go.

Happy for some help though @shouston3!

**Comment by samhstn** [comment]
I think you should divide up each of the issues outlined in https://github.com/dwyl/tudo/issues/238#issuecomment-329474169 into separate issues and we can discuss/plan/time estimate each one separately

**Comment by finnhodgkin** [comment]
I've added both unfinished issues to separate issues. 

I'll outline my plan for each in the comments :+1:
