### ISSUE TITLE
Landing Page Copy (That Converts!)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#24]
Turn our **Why?** into landing page copy that helps people identify with the problem(s) and makes them want to sign up and _use_ the product!

Right now we have:
<img width="941" alt="tudo-login-page-copy-alpha" src="https://cloud.githubusercontent.com/assets/194400/8798706/2201706e-2f9c-11e5-8396-ebd5de0c4870.png">

**Comment by nelsonic** [comment]
@msmichellegar + @iteles would you mind crafting some great Landing Page copy we can use to get people _excited_ about using Tudo?

**Comment by nelsonic** [comment]
@msmichellegar created a landing page view:
![proposed-landing-page-view](https://cloud.githubusercontent.com/assets/10683087/8856303/ed930078-3161-11e5-9f84-edadadaa885a.png)

see: https://github.com/dwyl/tudo/issues/26#issuecomment-124163243

**Comment by nelsonic** [comment]
@msmichellegar & @iteles Can we have this:

![hansel](http://i.imgur.com/ZA5g9sh.png)

as our landing page image? :laughing: 

(_as in **Tudo** helps you **know exactly what you're working on today** unlike Hansel, he's so hot right now..._)

**Comment by iteles** [comment]
He's so hot right now.

**Comment by msmichellegar** [comment]
I approve!

**Comment by Jbarget** [comment]
closing as now incorporated into: https://github.com/dwyl/tudo/issues/172
