### ISSUE TITLE
Clickable issue labels to filter results

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/tudo#242]
To speed up issue searching, each label tag (shown below) should also act as a link that filters results.

![peek 2017-09-14 16-38](https://user-images.githubusercontent.com/22300773/30439242-1f088a24-996b-11e7-835a-39ec9e78fea3.gif)

#238

**Comment by finnhodgkin** [comment]
Issue search currently works by adding a large query string to the end of all the pagination links / get requests via forms / links.

The previous search results are stored on `conn.query_string` so I should be able to make each label a link with a target of `/? + conn.query_string + a custom parameter based on the label name`.

**Comment by finnhodgkin** [comment]
I've got it working on desktop but not on the mobile card.

@shouston3 can view functions be included in components or do they need to be passed in as parameters.

I passed the function in as a param :+1:

**Comment by samhstn** [comment]
I'm pretty sure you can pass view functions to components without having to pass it as a parameter.
Have you tried importing the helper functions in the `web/web.ex` file.
