### ISSUE TITLE
Error running seed file

### ISSUE THREAD

**Issue by Jbarget** [dwyl/tudo#247]
following the Getting Started instructions when i run `mix run priv/repo/seeds.exs` i get:

![screen shot 2017-09-15 at 12 51 37](https://user-images.githubusercontent.com/11725595/30481082-c401d43c-9a14-11e7-9ece-88a763bb4982.png)

Environment variables have been exported so just wondering if theres a change i need to know about

**Comment by ZooeyMiller** [comment]
Do you have a `HOOK_ENDPOINT` set? I didn't have one so had to comment out lines 13, 14 and 20 in order to run the seed file.

**Comment by Jbarget** [comment]
fails at the same line unfortunately,  `(tudo) web/github/github_api.ex:49: Tudo.GithubApi.get_repos/3`

**Comment by ZooeyMiller** [comment]
Hm, I'm getting the same error when I run the file. Will have a look into what the problem is.

**Comment by finnhodgkin** [comment]
It's working perfectly on mine. Weird. 
We're comparing our machines now... @ZooeyMiller and I have the same access token so I don't _think_ it's permissions related.

**Comment by ZooeyMiller** [comment]
@Jbarget can you try deleting your `mix.lock` and re-running `mix deps.get` then trying the seed file again? Worked for me.

**Comment by Jbarget** [comment]
worked 👍
