### ISSUE TITLE
Remove Materialise CSS and replace with regular CSS

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/tudo#26]
Materialise CSS was added by @nelsonic as an interim solution for the authentication page. This needs to be replaced with regular CSS by the frontend team.

From: https://github.com/dwyl/tudo/pull/25

**Comment by iteles** [comment]
This was removed from `login.tag` in pull request #64: https://github.com/dwyl/tudo/blob/ced7cdfc6fafca532f275557a80c17333ce895cd/views/login.tag

It was removed from `layout_header.html` by @SimonLab and @benjaminlees in this commit:
https://github.com/dwyl/tudo/commit/e38ad8a2a8ee53aa816458a89f1523f2cc429a68

**Comment by msmichellegar** [comment]
![proposed-landing-page-view](https://cloud.githubusercontent.com/assets/10683087/8856303/ed930078-3161-11e5-9f84-edadadaa885a.png)
