### ISSUE TITLE
Investigate Programatically Creating Labels to Issues via GitHub API

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#3]
We can _set_ labels: https://developer.github.com/v3/issues/#edit-an-issue
Question is: can we _create_ a **_new**_ label for a repo using the API?

**Comment by iteles** [comment]
Looks like we can relatively easily: https://developer.github.com/v3/issues/labels/#create-a-label

**Comment by besarthoxhaj** [comment]
Working on this, right now. Related also to **Custom Labels** from https://github.com/dwyl/tudo/issues/34
