### ISSUE TITLE
Time labels in minutes or hours?

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/tudo#32]
Should "time-estimate" and "time-actual" labels display in the UI as hours or minutes?

As in: "time-estimate:300" vs. "time-estimate:5hrs".

What is more intuitive? And what is more effective for team management?

@NataliaLKB suggested A/B testing this later down the line.

**Comment by iteles** [comment]
**Starting point:** Input on the frontend be done in hours and minutes to start with and translated into minutes for the backend.

**Comment by NataliaLKB** [comment]
Personally I think we should display in the UI as 5 hrs as a first iteration. 
For me that seems more intuitive.

**Comment by nelsonic** [comment]
Most people intuitively understand minutes up to a number depending on their reference point.
e.g: 
- People who watch/play sports will think in terms of **90mins**
- People who  watch lots of movies will be comfortable with **126mins**

My suggestion would be: everything over `{X}m` minutes should be displayed as `{H}h` (_preferably **rounded down** to the nearest hour_)

But, we need to figure out how to A/B test this... and ask for feedback from people _using_ **Tudo**.

**Comment by msmichellegar** [comment]
I agree. I think minutes beyond about 120 are less intuitive, and we don't want people to struggle to convert minutes to hours in their heads every time they use our UI.

**Comment by iteles** [comment]
This was assigned to me as it requires A/B testing, but seeing as we're A/B testing _all_ of what we're doing, I think this is a mis-leading assignment. A label would be better!

**Comment by nelsonic** [comment]
@iteles I'm creating the labels for _current_ project on https://github.com/FAC-GM/app/labels 

using Upper Case **T** in the Label to denote Time and **_lower case**_ **m** or **h** to denote _minutes_ or _hours_. any _objections_? (_you can always change these later ... they aren't set in stone._)

**Comment by samhstn** [comment]
We've been happily using `hours` in our labels. We can reopen if this becomes an issue
