### ISSUE TITLE
Custom Labels

### ISSUE THREAD

**Issue by jrans** [dwyl/tudo#34]
These are our initial ideas:

Prioritisation: (numbers preferred atm)
- high/1
- med/2
- low/3

Agile:
- ice-box
- "replace milestones with sprint:

Time:
- Time estimated in minutes
- Time unestimated
- Time actual (on completion)

Other:
- dependency

WorkFlow:
- ???

Expense:
- ???

Techincal Task:
- Refactor...

**Comment by jrans** [comment]
Create a glossary please @benjaminlees

**Comment by jrans** [comment]
Any more ideas?

**Comment by besarthoxhaj** [comment]
@jrans starting now to have a look at this. Any idea where to start?

**Comment by nelsonic** [comment]
@jrans what still needs to be done for this?

**Comment by nelsonic** [comment]
Are we going to let people pick the colors for custom labels or encourage them to use pre-defined colors (so that the experience will be consistent across repos/orgs) ?

**Comment by iteles** [comment]
At the time we mentioned pre-defined colours to encourage consistency.

The only real downside here is that our pre-defined colours may clash with other existing labels for organisations that want to use _tudo_. If we stay 'off the beaten path' of standard Github colours, then we might not run into this problem as much.

_This question might deserve its own issue._ :wink:

**Comment by samhstn** [comment]
Labels issues seem to have been moved to [dwyl/labels](https://github.com/dwyl/labels/issues) and I think we've been working fine with the currently decided on labels.
