### ISSUE TITLE
API - Comments of an issue 

### ISSUE THREAD

**Issue by jrans** [dwyl/tudo#39]
@nofootnotes @NataliaLKB 

The issue objects we receive back from the call to get issues assigned to a person only contains the number of comments on an issue not the comments themselves.

Investigation needs to be done but think you'll need to make an API call for each issue to get these details plus others? 

When doing this would be nice to get an example of  the complete issue object.

Thanks,

Jack

**Comment by NataliaLKB** [comment]
Cool! Will work on this tomorrow.

**Comment by jrans** [comment]
Great work guys!
