### ISSUE TITLE
Create riot components from HTML structure files

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/tudo#45]
@iteles and I have created some HTML structure files for the server-side rendering people to have a structure to render with.

These are required as riot `.tag` files, so we need to convert the html structure into riot-friendly files.

**Comment by nelsonic** [comment]
@msmichellegar please reference the commit hash where these HTML structure files were created so the person trying to follow along does not have to go hunting. thanks! :+1:

**Comment by msmichellegar** [comment]
Full HTML structures for home and issue view were added here: https://github.com/dwyl/tudo/commit/30d778ce3ee48a6a917dec7a12a8cabc80e29f7a

However most up-to-date versions (with only a few minimal changes in the issues view) are in this pull request (waiting to be merged!): https://github.com/dwyl/tudo/pull/55

**Comment by iteles** [comment]
HTML structures superseded by UI sketches in #91 (same base) and the issue #107

**Comment by iteles** [comment]
Currently being done by/assigned to **[dwyl/team-beach]**.

**Comment by samhstn** [comment]
No longer using `riot`, closing
