### ISSUE TITLE
Create HTML structure for files

### ISSUE THREAD

**Issue by iteles** [dwyl/tudo#47]
We need to put together some HTML structure for the server-side team rendering to know what they are rendering!

**Comment by nelsonic** [comment]
@iteles what still needs to be "_decided_"?
_Where_ is the _proposal_ and request for discussion/decision?
because otherwise this issue is _worse_ than _useless_... :panda_face: :cry:

**Comment by iteles** [comment]
We needed to have an issue to work against whilst @msmichellegar and I put together our proposed HTML structure. The _proposal_ is what this issue is here for and we were open to suggestions, hence the 'help wanted' label.
These needed to be put together as quickly as possible so that we weren't a bottleneck for the server-side rendering tasks, such as #45.

This is now done in its most basic form for the MVP and added as PR #55 .

**Comment by iteles** [comment]
This was completed with PR #64 with the [addition of login.html](https://github.com/dwyl/tudo/blob/6f99d727b2ace2d67509fd0493859b96825ef535/html-structures/landing.html) into the temporary `html_structures` folder, but it appears to not have filtered through to the master. 

The `html_structures` folder is a temporary folder intended to be deleted as soon as `.tag` files have been completed, but it is still odd that these changes haven't been added.

Interestingly, the changes made to [login.tag](https://github.com/dwyl/tudo/blob/6f99d727b2ace2d67509fd0493859b96825ef535/views/tags/login.tag) and the [CSS](https://github.com/dwyl/tudo/blob/6f99d727b2ace2d67509fd0493859b96825ef535/public/main.css) in the same PR _have_ appeared in the `master` branch. @SimonLab Any idea why?

**Comment by iteles** [comment]
Closing this as superseded by the UI sketches in #91 and the issue in #107
