### ISSUE TITLE
Pure CSS toggle switch

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/tudo#48]
@iteles and I are on a quest to code a CSS-only toggle for the issue page. Right now we're using radio buttons, but we might be using checkboxes. Stay tuned!

**Comment by iteles** [comment]
HTML so far, commit https://github.com/dwyl/tudo/commit/c31e3c114451c7b1e1242c089980e0aa8c0fa1a4

``` html
<div class="toggle">
        <label for="latest-comment">Latest comment</label>
        <input type="radio" id="latest-comment" name="toggle" checked="checked"/>
        <label for="all-comments">All comment</label>
        <input type="radio" id="all-comments" name="toggle"/>
      </div>
```

**Comment by nelsonic** [comment]
_Where_ is the Toggle? (_**please** be **explicit/specific** so the person reviewing the issue for "**done**" will have an easier life..._)
e.g: 

![initial-homepage-and-issue-app-screens-toggle](https://cloud.githubusercontent.com/assets/194400/8847296/65415896-3125-11e5-8c62-dd64a2caddaf.png)

**Comment by iteles** [comment]
http://cssdeck.com/labs/better-css-toggle-switches

**Comment by iteles** [comment]
A toggle is no longer part of the current MVP as we've decided that the MVP will just link straight through to the issues on github :+1: _Minimum_ indeed.
