### ISSUE TITLE
Can/Should we use Primus instead of (or with) Socket.io?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#5]
What are the advantages of using primus?
https://github.com/primus/primus

**Comment by nelsonic** [comment]
@besarthoxhaj have you done a bit more investigation into WebSocket libraries? which one is the most reliable?

**Comment by besarthoxhaj** [comment]
Me and @benjaminlees wanted to dig into socket.io and see what they were doing. Did not have the time to do it yet.

However must say that love the readme of primus, is more beginner friendly.
Should we have brief brainstorming this late afternoon and talk about it?

**Comment by nelsonic** [comment]
@besarthoxhaj if you & @benjaminlees  have time to do the research and determine which WebSocket wrapper is the most reliable & performant (adds the least overhead to the protocol) and put this research into a markdown file, it would be _awesome_!

**Comment by iteles** [comment]
@besarthoxhaj From what I hear, you're pretty busy these days! Should we re-assign this?

**Comment by besarthoxhaj** [comment]
Hi guys!
Really sorry for my absence. @iteles as you said I'm not sure if I can give the right amount of time needed for the task. Feel free to assign someone else:)

**Comment by nelsonic** [comment]
Phoenix Channels to the Rescue! ❤️
