### ISSUE TITLE
Mysteriously disappearing bottom border in mobile view

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/tudo#54]
CSS does crazy things. We have a weird issue where our bottom borders disappears in the Chrome mobile view. This is not a problem when we open it without the mobile view, or in any other browsers.

Must investigate this behaviour to figure out if it's a real mobile view issue, or just a Chrome dev tools issue.

Desktop view:
![bottom-border-appears-in-desktop-view](https://cloud.githubusercontent.com/assets/4185328/8847155/0a7b4440-3124-11e5-8ec2-35d1a8fae132.png)

Mobile view in Chrome:
![bottom-border-disappears-in-mobile-view](https://cloud.githubusercontent.com/assets/4185328/8847156/0a9d2092-3124-11e5-9c6d-65e652f3a6c6.png)

**Comment by nelsonic** [comment]
@msmichellegar is this _reproducible_ on the _actual_ device or is it specific to the Chrome emulator?

**Comment by msmichellegar** [comment]
@nelsonic We are yet to test this. Just leaving this issue here so we know to come back and figure that out.

**Comment by iteles** [comment]
Closing this as it doesn't appear to be an issue for the current iteration (so odd)! May re-open this if it re-occurs.

(and let's not worry, this is **_not_** the final styling)

<img width="342" alt="All border bottoms show up in Chrome emulator view" src="https://cloud.githubusercontent.com/assets/4185328/9366518/c9bdb446-46af-11e5-8645-989f75df0728.png">
