### ISSUE TITLE
Riot tags issues // create the tags for the issues page

### ISSUE THREAD

**Issue by anniva** [dwyl/tudo#58]
issue_page_container.tag
 issue_title.tag
 label_container.tag
 issue_description.tag
 comment_container.tag
   latest_comment.tag
   all_comments.tag

**Comment by msmichellegar** [comment]
Are these tags that have been created?

**Comment by iteles** [comment]
@anniva Note that this morning when we were determining data, we decided we'd display only the latest comment for now and add 'all comments' in the next iteration :blush:

**Comment by iteles** [comment]
This is already being captured in #45 and being worked on in the August group of [#dwylsummer](https://github.com/dwyl/summer-2015).
