### ISSUE TITLE
GitHub Authentication

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#6]
one of the first steps is getting GitHub authentication working. who wants (has time) to work on this?

> _Most_ of us have built apps that included some form of GitHub authentication. 
> The interesting thing here is ensuring our app has _**tests**_!

**Comment by nelsonic** [comment]
![github-sign-in](https://cloud.githubusercontent.com/assets/194400/8786882/be2842de-2f28-11e5-8fd9-2022cba21e31.png)

**Comment by nelsonic** [comment]
![gitHub-logo-with-octocat](http://i.imgur.com/OpgVViO.jpg)

**Comment by nelsonic** [comment]
@benjaminlees what do you think about this:
<img width="827" alt="tudo-login-with-github" src="https://cloud.githubusercontent.com/assets/194400/8788330/8b4d03dc-2f31-11e5-9ec8-795a0ffdbe8a.png">

**Comment by Jbarget** [comment]
closing as this is now merged in with the new phoenix project: https://github.com/dwyl/tudo/commit/5529332572e5424f8c7d30297d17faf213c0a8bb
