### ISSUE TITLE
CSS | Investigate styling of issue label colours

### ISSUE THREAD

**Issue by iteles** [dwyl/tudo#72]
Labels can be given **any** colour so there is no _predictable_ set that we can code into the CSS file.

We need to investigate what the best way to ensure we can provide the right colour of background to the labels is. This will _ideally_ be done **without** inline styling as github uses in some places (oddly).
<img width="819" alt="github-inline-styling" src="https://cloud.githubusercontent.com/assets/4185328/8857703/37b5e126-316b-11e5-9e52-e2546e7477d1.png">

And **hopefully** we can find a better solution than generating a class for each and every colour.

**Comment by nelsonic** [comment]
What is the problem with dynamically setting the color an in-line style in the tag (_view_) ?
(this is far less complex than having an ever expanding list of colors in the CSS file...
e.g: `views/label.tag`

``` html
<label><a style="#{label.color}" href="/issues?filter={label.name}">{label.name}</a></label>
```

**Comment by iteles** [comment]
I avoid inline styles as a rule because they are detrimental to:
- **Accessibility:** There are groups of people who navigate the web with custom stylesheets which are **always** _overriden by inline styles_ - for example, significantly colour blind people use custom stylesheets to allow them to see fonts overlayed on specific colours;
- **Readability:** It clutters the code, especially in this case where you would have a lot of them in close proximity

It also:
- Sets a bad example and people working with dwyl might think it's acceptable to style inline for no particular reason
- Attracts hecklers unnecessarily who will attack our code quality because it doesn't [separate concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) - if we don't have to deal with them, better.

Worth noting that given the _relatively small_ number of inline styles in this case, it probably wouldn't affect page load times.

**Comment by iteles** [comment]
And then there's [this CSS tricks article](https://css-tricks.com/the-debate-around-do-we-even-need-css-anymore/) which beautifully sums up the arguments for and against inline styling.

**Comment by nelsonic** [comment]
I _obviously_ prefer _**not**_ to have _inline styles_ @iteles 
I look forward to seeing how this gets resolved (_in an **elegant** way_) without _inline styles_ ... :+1:

**Comment by samhstn** [comment]
This may have been relevant to the `old_project`, but should not be an issue in this one as we will be adding colors by adding classes and won't be using inline styles
