### ISSUE TITLE
Investigate visual regression testing

### ISSUE THREAD

**Issue by iteles** [dwyl/tudo#79]
[PhantomCSS](https://github.com/Huddle/PhantomCSS) seems quite popular and the [BBC uses its own framework](http://bbc-news.github.io/wraith/index.html).

Also,
- [ ] [Galen to test for responsiveness](http://davidwalsh.name/automated-tests-visual-responsive-layouts)
- [ ] http://www.gizra.com/content/visual-regression-travis-shoov-ngrok/
- [ ] https://css-tricks.com/automating-css-regression-testing/

**Comment by nelsonic** [comment]
Could we ("just") take screenshots for now: https://github.com/sindresorhus/pageres ?

**Comment by iteles** [comment]
Will try using https://github.com/sindresorhus/pageres-cli to screenshot a site running locally (no examples of this in docs).

**Comment by iteles** [comment]
Opened a repo for this under https://github.com/iteles/visual-regression-testing which will be moved to dwyl when it's a learning resource rather than a catch-all for research.

**Comment by nelsonic** [comment]
Exciting! :wink:

**Comment by iteles** [comment]
Closing this issue as it's no longer most relevant here.
