### ISSUE TITLE
Should we have an "out of scope" label?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#80]
![grumpy cat out of scope](http://cdn.meme.am/instances/500x/62805514.jpg)

Should we have an `out of scope` label to clearly signal when an issue is not part of the current requirement?
- https://en.wikipedia.org/wiki/Scope_(project_management)
- http://www.techrepublic.com/blog/it-consultant/define-project-scope-to-include-deliverables-boundaries-and-requirements/

relates to: https://github.com/dwyl/tudo/issues/34 (custom labels)

**Comment by iteles** [comment]
I think this would be useful.

We'll need to clearly differentiate between `invalid` and `out of scope` label definitions.

**Comment by nelsonic** [comment]
@iteles what do _you_ see as the difference between `invalid` and `out of scope` ...?

**Comment by iteles** [comment]
My view on these would be:
- `invalid` is an issue which is not actually an issue. This could be an issue outside of our control such as a personal computer problem or anything like 'the app isn't pink enough for me, you should make it pink' (I would consider this issue invalid but open an issue around custom colour themes).
- `out of scope` is a perfectly plausible issue or feature request, but isn't something we can dedicate time to right now. It might come down the line or it could be picked up by anyone wishing to work on it.

I've personally never used an `invalid` label. If something is genuinely not an issue I would just explain why and close it.

**Comment by samhstn** [comment]
@nelsonic @iteles has this been resolved and we can close this? If not we can migrate this to `dwyl/labels`

**Comment by iteles** [comment]
@shouston3 Agree this is no longer relevant in this repo.

Moved to https://github.com/dwyl/labels/issues/75
