### ISSUE TITLE
version of tudo on heroku is broken 

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/tudo#86]
![screen shot 2015-08-17 at 14 32 07](https://cloud.githubusercontent.com/assets/5912647/9305895/ca5c0912-44ec-11e5-9e41-01c2c0b78ce2.png)

**Comment by nelsonic** [comment]
![tudo-heroku-nodemon-error](https://cloud.githubusercontent.com/assets/194400/9307346/0a1956be-44f6-11e5-9541-5887cf86c9fb.png)

**Comment by nelsonic** [comment]
![tudo-landing-page-heroku-working](https://cloud.githubusercontent.com/assets/194400/9307506/dc0e445e-44f6-11e5-8a46-ff633f4bd05f.png)

**Comment by nelsonic** [comment]
@nikhilaravi please confirm this is working now. thanks! :+1:

**Comment by nikhilaravi** [comment]
@nelsonic its looking good :+1:

**Comment by nelsonic** [comment]
Sweet! :lollipop:
