### ISSUE TITLE
Create Dummy GitHub User for use in End-to-End Tests

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#9]
As per title. we need a Dummy GitHub User we can use in tests.

**Comment by dwyltest** [comment]
@iteles   I have created a dummy github account to review the details see https://docs.google.com/document/d/1uztGvSE8nxjQwJtCorQUiNM9irjIoomhFuhLfghDC0o/edit

**Comment by benjaminlees** [comment]
@iteles that last message came from the dummy

**Comment by iteles** [comment]
:+1: Looks good, thanks @benjaminlees!
