### ISSUE TITLE
What should the order of priority labels be? (is P1 highest priority or P5?)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tudo#93]
So, we've agreed that **_Tudo**_'s most useful **MVP** feature is prioritising issues.
But we haven't yet agreed what he **_highest**_ priority label should be.

We **_discussed**_ _recommending_ several levels of priority to people e.g:  
 `Priority-1`(`P1`) >> `Priority-5` (`P5`)

But ... is `P1` the **_highest**_ priority or `P5` (when using a 5-level scale) ? @dwyl/summer

**Comment by beechware** [comment]
P1 = Defcon1!! Let's make it happen

**Comment by iteles** [comment]
I'm a fan of Priority 1 (highest priority) to Priority 5.
For me, that means that 'things that will be worked on at a later date' or 'icebox' things, will all go down to 5 and be _out of my way_ when I'm actually working through things that need to be done.

**Comment by jackpandas** [comment]
I would vote 1 as the highest priority

**Comment by minaorangina** [comment]
1 > 5 :rotating_light:

**Comment by tsop14** [comment]
1 = highest priority

**Comment by samhstn** [comment]
This has been decided on and implemented in `dwyl/labels`, closing
