### ISSUE TITLE
Raising low priority issues up to higher priority periodically and automatically

### ISSUE THREAD

**Issue by beechware** [dwyl/tudo#96]
This would be to stop Low priority (non-urgent) issues from being left and forgotten about.

E.g P5 moves to P4 after 24 hours (or however long) and so on and so forth.

**Comment by tsop14** [comment]
It is good to try to prevent issues being left forever but it might be confusing if we can't tell what was manually asigned by the user and what was an automatic change.

**Comment by samhstn** [comment]
This is no longer relevant to the current project plan
